# Generated by Django 4.2.3 on 2024-09-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='manager_unique_id',
            new_name='unique_id',
        ),
    ]
