# Generated by Django 4.2.3 on 2024-09-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_rename_manager_unique_id_manager_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
