# Generated by Django 4.2.3 on 2024-09-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='manager_id',
            new_name='manager',
        ),
    ]
