# Generated by Django 4.2.3 on 2024-09-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_rename_manager_id_employee_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updatedat',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='updatedat',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='date_joined',
            field=models.DateField(),
        ),
    ]
